### ISSUE TITLE
Validation to-do

### ISSUE THREAD

**Issue by pauhidalgoo** [caiselvas/language-identification#2]
There are some basic functions for validation, and most of the code is prepared for it. However, currently it only gathers the number of errors (but maybe we should try other metrics). It remains to-do:

- [x] Determine if B values should be from validation
- [x] (Conditional) If they are from validation, implement a way to change them
- [x] Write some code to gather statistics about each iteration step.
- [x] Execute validation and get parameters
